name: "postrrboard-dev-db-only"
services:

  just-mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    
    command: [--auth]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    tty: true
    volumes:
      - ./mongo-scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - /data/db

